language: ruby
cache: bundler
before_install: gem update bundler
rvm:
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'
  - '2.7'
  - '3.0'
  - ruby-head
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: '3.0'
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 'ruby-head'
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: '2.2'
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: '2.3'
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: '2.4'
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: '2.2'
      gemfile: gemfiles/rails_6_1.gemfile
    - rvm: '2.3'
      gemfile: gemfiles/rails_6_1.gemfile
    - rvm: '2.4'
      gemfile: gemfiles/rails_6_1.gemfile
    - rvm: '2.2'
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: '2.3'
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: '2.4'
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: '2.5'
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: '2.6'
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
notifications:
  email: false
